//Joe McCourt
//4/15/12

// Project Euler problem 12
// The sequence of triangle numbers is generated by adding 
// the natural numbers. So the 7th triangle number would be 
// 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number 
// to have over five divisors.
// What is the value of the first triangle number 
// to have over five hundred divisors?
function Prob12(){
	this.numFactors = function(number){
		if(number==1){return 1;}
		var factors = 2;
		var d = 2;
		while(d*d <= number){
			if(!(number%d)){
				//console.log(d,number/d);
				if(d*d==number){factors+=1;}else{factors+=2;}
				//number/=d;
			}
			d++;
		}
		return factors;
	};

	this.eval = function(max){
		var triangle = 1;
		var factors = 1;
		var count = 2;
		var nth = 1;
		while(factors <= max){
			nth++;
			triangle = nth*(nth+1)/2;
			factors = this.numFactors(triangle);
		}
		return nth*(nth+1)/2;
	};
}