// Joe McCourt
// 7/22/12

// Pentagonal numbers are generated by the formula,
// Pn=n(3n-1)/2. The first ten pentagonal numbers are:
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
// It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
// However, their difference, 70 - 22 = 48, is not pentagonal.
// Find the pair of pentagonal numbers, Pj and Pk, for which
// their sum and difference is pentagonal and D = |Pk - Pj| is minimised;
// what is the value of D?

// Pj = j(3j-1)/2, Pk = k(3k-1)/2
// Pj + Pk = s(3s-1)/2, Pj - Pk = d(3d-1)/2
// s(3s-1)/2 = j(3j-1)/2 + k(3k-1)/2
// s(3s-1) = j(3j-1) + k(3k-1)
// d(3d-1) = j(3j-1) - k(3k-1)
// s(3s-1) + d(3d-1) = 2*j(3j-1)
// s(3s-1) - d(3d-1) = 2*k(3k-1)

function penta(n){return n*(3*n-1)/2;}

//Known n is bigger
function isPentaBiggerN(value,n){
	var pn = penta(n);
	while(pn > value){
		pn = penta(n);
		n--;
	}
	if(pn == value){return true;}
	return false;
}

//Known n is smaller
function isPentaSmallerN(value,n){
	var pn = penta(n);
	while(pn < value){
		pn = penta(n);
		n++;
	}
	if(pn == value){return true;}
	return false;
}

var max = 10000;
for(var j = 1; j < max; j++){
	for(var k = j+1; k < max; k++){
		if(isPentaSmallerN(penta(j)+penta(k),k)&&isPentaBiggerN(penta(k)-penta(j),k)){
			console.log(penta(k)-penta(j));
			return;  //The first one I found just happend to be the answer
		}
	}
}