//Joe McCourt
//4/14/12

// Project Euler problem 2
// Each new term in the Fibonacci sequence is generated by adding the previous two terms
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.
function Prob2(){

	this.isMultiple = function(number,base){
		return !(number%base);
	};

	var fibHigher = 2;
	var fibLower = 1;
	var answer = 0;

	while(fibHigher <= 4000000){
		//Sum if even
		if(isMultiple(fibHigher,2)){
			answer += fibHigher;
		}

		//update fibinaci numbers
		var tempHigher = fibHigher;
		fibHigher += fibLower;
		fibLower = tempHigher;
	}
	
	return answer;
}