// Joe McCourt
// 7/22/12

// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
// Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
// Hexagonal	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.
// Find the next triangle number that is also pentagonal and hexagonal.

function tri(n){return n*(n+1)/2;}
function penta(n){return n*(3*n-1)/2;}
function hexa(n){return n*(2*n-1);}

//Hexagonal numbers are least dense, so search through those
var t = 1;
var p = 1;
var numHex = 1;
var numPen = 1;
var numTri = 1;
for(var h = 1; h < 100000; h++){
	var numHex = hexa(h);
	while(numTri < numHex){t++;numTri=tri(t);}
	while(numPen < numHex){p++;numPen=penta(p);}

	if(numTri == numHex && numPen == numHex && h > 143){
		console.log(numHex);
	}
}

